# Copyright 2021 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python37

handlers:
  - url: /component-demos/(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/component-demos/\1
    upload: dist/component-demos/(.*)(|\.map)

  - url: /component-demos/(.*)
    static_files: dist/component-demos/index.html
    upload: dist/component-demos/index.html

  - url: /debug/graph/?$
    static_files: dist/web-prototyping-tool/debug/graph/index.html
    upload: dist/web-prototyping-tool/debug/graph/index.html

  - url: /(manifest\.json)
    static_files: dist/web-prototyping-tool/manifest.json
    upload: dist/web-prototyping-tool/manifest.json
    mime_type: application/manifest+json
    secure: always

  # App
  - url: /(ngsw\.json|ngsw-worker\.js|safety-worker\.js|worker-basic\.min\.js|ngsw_worker\.es6\.js\.map|session-refresh\.js)
    secure: always
    static_files: dist/web-prototyping-tool/\1
    upload: dist/web-prototyping-tool/.*
    expiration: '1s'

  - url: /(.+).(css|html|js|map)
    static_files: dist/web-prototyping-tool/\1.\2
    upload: dist/web-prototyping-tool/.*\.(css|html|js|map)

  - url: /(.+).(json|png|svg|gif|ico|zip|mp3|mp4)
    static_files: dist/web-prototyping-tool/\1.\2
    upload: dist/web-prototyping-tool/.*\.(json|png|svg|gif|ico)
    expiration: '1d'

  - url: /(.*)
    static_files: dist/web-prototyping-tool/index.html
    upload: dist/web-prototyping-tool/index.html
